services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8008
    volumes:
      - .:/app
    ports:
      - 8008:8008
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app